# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f886e752418abed84a3991ee689cfc931fe060ef71e8ea71c9a2270aa16b77e68003be94444d23c3b0530a06af608eb7d9a6c8429545ce2b9b7242e6b8a35fbb

test:
  secret_key_base: 437d2d8675439f52e07c327fb391254a3a0ac250195d1bd19bad309a810a1d765dd31226822440f8db8d586d92c4243e23ac6d9be276babb09e6d9e8ae71713c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
